// Mapeo de nombres de países a códigos ISO 3166-1 alpha-2
export const countryToCode = {
  // Países
  'Albania': 'al',
  'Alemania': 'de',
  'Andorra': 'ad',
  'Arabia Saudita': 'sa',
  'Argelia': 'dz',
  'Argentina': 'ar',
  'Armenia': 'am',
  'Aruba': 'aw',
  'Australia': 'au',
  'Austria': 'at',
  'Azerbaiyán': 'az',
  'Bahamas': 'bs',
  'Bahréin': 'bh',
  'Bangladesh': 'bd',
  'Barbados': 'bb',
  'Bélgica': 'be',
  'Belice': 'bz',
  'Benín': 'bj',
  'Bermudas': 'bm',
  'Bielorrusia': 'by',
  'Bolivia': 'bo',
  'Bosnia y Herzegovina': 'ba',
  'Botsuana': 'bw',
  'Brasil': 'br',
  'Brunei': 'bn',
  'Bulgaria': 'bg',
  'Burkina Faso': 'bf',
  'Camboya': 'kh',
  'Camerún': 'cm',
  'Canadá': 'ca',
  'Catar': 'qa',
  'Chad': 'td',
  'Chile': 'cl',
  'China': 'cn',
  'Chipre': 'cy',
  'Colombia': 'co',
  'Corea del Sur': 'kr',
  'Costa de Marfil': 'ci',
  'Costa Rica': 'cr',
  'Croacia': 'hr',
  'Curazao': 'cw',
  'Dinamarca': 'dk',
  'Dominica': 'dm',
  'Ecuador': 'ec',
  'Egipto': 'eg',
  'El Salvador': 'sv',
  'Emiratos Árabes': 'ae',
  'Eslovaquia': 'sk',
  'Eslovenia': 'si',
  'España': 'es',
  'Estados Unidos': 'us',
  'Estonia': 'ee',
  'Fiji': 'fj',
  'Filipinas': 'ph',
  'Finlandia': 'fi',
  'Francia': 'fr',
  'Gabón': 'ga',
  'Georgia': 'ge',
  'Ghana': 'gh',
  'Gibraltar': 'gi',
  'Granada': 'gd',
  'Grecia': 'gr',
  'Guadalupe': 'gp',
  'Guam': 'gu',
  'Guatemala': 'gt',
  'Guyana': 'gy',
  'Haití': 'ht',
  'Honduras': 'hn',
  'Hong Kong': 'hk',
  'Hungría': 'hu',
  'India': 'in',
  'Indonesia': 'id',
  'Irán': 'ir',
  'Irlanda': 'ie',
  'Islandia': 'is',
  'Israel': 'il',
  'Italia': 'it',
  'Jamaica': 'jm',
  'Japón': 'jp',
  'Jordania': 'jo',
  'Kazajistán': 'kz',
  'Kenia': 'ke',
  'Kuwait': 'kw',
  'Laos': 'la',
  'Letonia': 'lv',
  'Líbano': 'lb',
  'Liechtenstein': 'li',
  'Lituania': 'lt',
  'Luxemburgo': 'lu',
  'Macao': 'mo',
  'Madagascar': 'mg',
  'Malasia': 'my',
  'Maldivas': 'mv',
  'Malta': 'mt',
  'Marruecos': 'ma',
  'Martinica': 'mq',
  'Mauricio': 'mu',
  'México': 'mx',
  'Mónaco': 'mc',
  'Mongolia': 'mn',
  'Montenegro': 'me',
  'Mozambique': 'mz',
  'Myanmar': 'mm',
  'Nepal': 'np',
  'Nicaragua': 'ni',
  'Noruega': 'no',
  'Nueva Zelanda': 'nz',
  'Omán': 'om',
  'Países Bajos': 'nl',
  'Pakistán': 'pk',
  'Panamá': 'pa',
  'Perú': 'pe',
  'Polonia': 'pl',
  'Portugal': 'pt',
  'Puerto Rico': 'pr',
  'Reino Unido': 'gb',
  'República Checa': 'cz',
  'República Dominicana': 'do',
  'Rumania': 'ro',
  'Rusia': 'ru',
  'Senegal': 'sn',
  'Serbia': 'rs',
  'Seychelles': 'sc',
  'Singapur': 'sg',
  'Sri Lanka': 'lk',
  'Sudáfrica': 'za',
  'Suecia': 'se',
  'Suiza': 'ch',
  'Tailandia': 'th',
  'Taiwán': 'tw',
  'Tanzania': 'tz',
  'Trinidad y Tobago': 'tt',
  'Túnez': 'tn',
  'Turquía': 'tr',
  'Ucrania': 'ua',
  'Uganda': 'ug',
  'Uruguay': 'uy',
  'Vietnam': 'vn'
};

// Mapeo de ciudades a códigos de país
export const cityToCountryCode = {
  'Abu Dabi': 'ae',
  'Ámsterdam': 'nl',
  'Antalya': 'tr',
  'Atenas': 'gr',
  'Bali': 'id',
  'Bangkok': 'th',
  'Barcelona': 'es',
  'Berlín': 'de',
  'Bombay': 'in',
  'Boston': 'us',
  'Budapest': 'hu',
  'Cancún': 'mx',
  'Chicago': 'us',
  'Dubái': 'ae',
  'Dublín': 'ie',
  'El Cairo': 'eg',
  'Estambul': 'tr',
  'Hawaii': 'us',
  'Honolulu': 'us',
  'Ibiza': 'es',
  'Las Vegas': 'us',
  'Lisboa': 'pt',
  'Londres': 'gb',
  'Los Ángeles': 'us',
  'Madrid': 'es',
  'Mallorca': 'es',
  'Manila': 'ph',
  'Marrakech': 'ma',
  'Melbourne': 'au',
  'Miami': 'us',
  'Milán': 'it',
  'Montreal': 'ca',
  'Moscú': 'ru',
  'Nueva York': 'us',
  'Osaka': 'jp',
  'París': 'fr',
  'Pekín': 'cn',
  'Phuket': 'th',
  'Praga': 'cz',
  'Punta Cana': 'do',
  'Roma': 'it',
  'San Francisco': 'us',
  'Seattle': 'us',
  'Seúl': 'kr',
  'Shanghái': 'cn',
  'Sídney': 'au',
  'Tenerife': 'es',
  'Tokio': 'jp',
  'Toronto': 'ca',
  'Vancouver': 'ca',
  'Viena': 'at',
  'Washington D.C.': 'us',
  'Yakarta': 'id'
};

// Función helper para obtener el código de país
export const getCountryCode = (name: string): string | null => {
  return (countryToCode as any)[name] || (cityToCountryCode as any)[name] || null;
};

// Componente de bandera reutilizable
interface FlagIconProps {
  countryName: string;
  size?: string;
}

export const FlagIcon = ({ countryName, size = '1x' }: FlagIconProps) => {
  const code = getCountryCode(countryName);
  
  if (!code) {
    // Si no hay código, mostrar emoji genérico
    return <span>🌍</span>;
  }
  
  return <span className={`fi fi-${code} fis fis-${size}`}></span>;
};
